-- MySQL Script generated by MySQL Workbench
-- Sat 14 Mar 2020 10:27:02 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Ventas_Partes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ventas_Partes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ventas_Partes` ;
USE `Ventas_Partes` ;

-- -----------------------------------------------------
-- Table `Ventas_Partes`.`personal_ajepp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`personal_ajepp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `per_identificacion` VARCHAR(100) NOT NULL,
  `per_nombre` VARCHAR(30) NOT NULL,
  `per_apellido` VARCHAR(30) NOT NULL,
  `per_edad` INT NOT NULL,
  `per_genero` VARCHAR(2) NOT NULL,
  `fecha_ingreso` YEAR NULL,
  `per_domicilio` VARCHAR(100) NULL,
  `per_dirreccion` VARCHAR(100) NULL,
  `personal_ajeppcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `per_identificacion_UNIQUE` (`per_identificacion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`Login` (
  `usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `Tabla_Personal_Id_personal` VARCHAR(60) NOT NULL,
  `permiso` INT NULL,
  PRIMARY KEY (`usuario`, `Tabla_Personal_Id_personal`),
  INDEX `fk_Login_Tabla_Personal1_idx` (`Tabla_Personal_Id_personal` ASC),
  CONSTRAINT `fk_Login_Tabla_Personal1`
    FOREIGN KEY (`Tabla_Personal_Id_personal`)
    REFERENCES `Ventas_Partes`.`personal_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`tipo_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`tipo_vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_vehiculo` VARCHAR(60) NOT NULL,
  `clasificacion_vehiculo` VARCHAR(60) NOT NULL,
  `vehiculo_img` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`marca_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`marca_vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca_vehiculo` VARCHAR(60) NOT NULL,
  `mar_img` VARCHAR(45) NULL,
  `tipo_vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_vehiculo_id`),
  INDEX `fk_marca_vehiculo_tipo_vehiculo1_idx` (`tipo_vehiculo_id` ASC),
  CONSTRAINT `fk_marca_vehiculo_tipo_vehiculo1`
    FOREIGN KEY (`tipo_vehiculo_id`)
    REFERENCES `Ventas_Partes`.`tipo_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`modelo_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`modelo_vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca_vehiculo_id` INT NOT NULL,
  `mod_vehiculo` VARCHAR(100) NOT NULL,
  `mod_anio` YEAR NOT NULL,
  `mod_img` VARCHAR(45) NULL,
  `procedencia` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `marca_vehiculo_id`),
  INDEX `fk_modelo_vehiculo_marca_vehiculo1_idx` (`marca_vehiculo_id` ASC),
  CONSTRAINT `fk_modelo_vehiculo_marca_vehiculo1`
    FOREIGN KEY (`marca_vehiculo_id`)
    REFERENCES `Ventas_Partes`.`marca_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`clasificacion_pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`clasificacion_pieza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cla_tipo` VARCHAR(45) NULL,
  `pie_img` VARCHAR(100) NULL,
  `modelo_vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `modelo_vehiculo_id`),
  INDEX `fk_clasificacion_pieza_modelo_vehiculo1_idx` (`modelo_vehiculo_id` ASC),
  CONSTRAINT `fk_clasificacion_pieza_modelo_vehiculo1`
    FOREIGN KEY (`modelo_vehiculo_id`)
    REFERENCES `Ventas_Partes`.`modelo_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`detalles_pieza_tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`detalles_pieza_tienda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pie_serie` VARCHAR(100) NOT NULL,
  `pie_precio` FLOAT NOT NULL,
  `pie_detalles` TEXT NOT NULL,
  `pie_cantidad` INT NOT NULL,
  `clasificacion_pieza_id` INT NOT NULL,
  `pie_t_img` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `clasificacion_pieza_id`),
  INDEX `fk_detalles_pieza_tienda_clasificacion_pieza1_idx` (`clasificacion_pieza_id` ASC),
  CONSTRAINT `fk_detalles_pieza_tienda_clasificacion_pieza1`
    FOREIGN KEY (`clasificacion_pieza_id`)
    REFERENCES `Ventas_Partes`.`clasificacion_pieza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`personal_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`personal_contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `per_email` VARCHAR(100) NULL,
  `per_celular` VARCHAR(45) NOT NULL,
  `per_telefono_casa` VARCHAR(45) NULL,
  `per_twiter` VARCHAR(45) NULL,
  `personal_ajepp_id` INT NOT NULL,
  PRIMARY KEY (`id`, `personal_ajepp_id`),
  UNIQUE INDEX `Email_UNIQUE` (`per_email` ASC),
  INDEX `fk_personal_contacto_personal_ajepp1_idx` (`personal_ajepp_id` ASC),
  CONSTRAINT `fk_personal_contacto_personal_ajepp1`
    FOREIGN KEY (`personal_ajepp_id`)
    REFERENCES `Ventas_Partes`.`personal_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(100) NOT NULL,
  `cli_nombres` VARCHAR(100) NOT NULL,
  `cli_apellidos` VARCHAR(100) NOT NULL,
  `cli_edad` INT NOT NULL,
  `cli_genero` VARCHAR(2) NOT NULL,
  `cli_domicilio` VARCHAR(100) NULL,
  `cli_dirreccion` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`datos_contacto_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`datos_contacto_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `cli_correro` VARCHAR(100) NULL,
  `cli_telefono` VARCHAR(60) NULL,
  `cli_twiter` VARCHAR(50) NULL,
  `cli_facebook` VARCHAR(50) NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  INDEX `fk_datos_contacto_cliente_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_datos_contacto_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Ventas_Partes`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`vehiculo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`vehiculo_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `serie` VARCHAR(150) NOT NULL,
  `veh_tipo` VARCHAR(60) NULL,
  `veh_anio` YEAR NULL,
  `veh_modelo` VARCHAR(60) NULL,
  `veh_marca` VARCHAR(45) NULL,
  `veh_img` VARCHAR(150) NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  UNIQUE INDEX `serie_UNIQUE` (`serie` ASC),
  INDEX `fk_vehiculo_cliente_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_vehiculo_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Ventas_Partes`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`departamento_ajepp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`departamento_ajepp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dep_nombre` VARCHAR(60) NULL,
  `dep_locacion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`cargo_ajepp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`cargo_ajepp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departamento_ajepp_id` INT NOT NULL,
  `car_nombre` VARCHAR(100) NULL,
  `pago_cargo` FLOAT NULL,
  PRIMARY KEY (`id`, `departamento_ajepp_id`),
  INDEX `fk_cargo_ajepp_departamento_ajepp1_idx` (`departamento_ajepp_id` ASC),
  CONSTRAINT `fk_cargo_ajepp_departamento_ajepp1`
    FOREIGN KEY (`departamento_ajepp_id`)
    REFERENCES `Ventas_Partes`.`departamento_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`cargo_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`cargo_personal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` VARCHAR(45) NULL,
  `per_salario` FLOAT NULL,
  `cargo_ajepp_id` INT NOT NULL,
  `personal_ajepp_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cargo_ajepp_id`, `personal_ajepp_id`),
  INDEX `fk_cargo_personal_cargo_ajepp1_idx` (`cargo_ajepp_id` ASC),
  INDEX `fk_cargo_personal_personal_ajepp1_idx` (`personal_ajepp_id` ASC),
  CONSTRAINT `fk_cargo_personal_cargo_ajepp1`
    FOREIGN KEY (`cargo_ajepp_id`)
    REFERENCES `Ventas_Partes`.`cargo_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargo_personal_personal_ajepp1`
    FOREIGN KEY (`personal_ajepp_id`)
    REFERENCES `Ventas_Partes`.`personal_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pro_nombre` VARCHAR(45) NULL,
  `pro_apellido` VARCHAR(45) NULL,
  `pro_edad` INT NULL,
  `pro_genero` VARCHAR(2) NULL,
  `pro_nacionalidad` VARCHAR(45) NULL,
  `pro_dirreccion` VARCHAR(150) NULL,
  `pro_img` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`tipo_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_pago` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`compra_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`compra_proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iva` FLOAT NOT NULL,
  `subtotal` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `fecha_compra` DATETIME NOT NULL,
  `detalle` TEXT NOT NULL,
  `personal_ajepp_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  `tipo_pago_id` INT NOT NULL,
  PRIMARY KEY (`id`, `personal_ajepp_id`, `proveedor_id`, `tipo_pago_id`),
  INDEX `fk_compra_proveedor_personal_ajepp1_idx` (`personal_ajepp_id` ASC),
  INDEX `fk_compra_proveedor_proveedor1_idx` (`proveedor_id` ASC),
  INDEX `fk_compra_proveedor_tipo_pago1_idx` (`tipo_pago_id` ASC),
  CONSTRAINT `fk_compra_proveedor_personal_ajepp1`
    FOREIGN KEY (`personal_ajepp_id`)
    REFERENCES `Ventas_Partes`.`personal_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_proveedor_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `Ventas_Partes`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_proveedor_tipo_pago1`
    FOREIGN KEY (`tipo_pago_id`)
    REFERENCES `Ventas_Partes`.`tipo_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`detalles_pieza_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`detalles_pieza_bodega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_proveedor_id` INT NOT NULL,
  `pie_serie` VARCHAR(100) NOT NULL,
  `pie_precio_venta` FLOAT NULL,
  `pie_precio_compra` FLOAT NOT NULL,
  `pie_fecha_ingreso` DATETIME NOT NULL,
  `pie_detalle` TEXT NOT NULL,
  `pie_cantidad` INT NOT NULL,
  `clasificacion_pieza_id` INT NOT NULL,
  `bod_t_img` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `compra_proveedor_id`, `clasificacion_pieza_id`),
  INDEX `fk_detalles_pieza_bodega_compra_proveedor1_idx` (`compra_proveedor_id` ASC),
  INDEX `fk_detalles_pieza_bodega_clasificacion_pieza1_idx` (`clasificacion_pieza_id` ASC),
  CONSTRAINT `fk_detalles_pieza_bodega_compra_proveedor1`
    FOREIGN KEY (`compra_proveedor_id`)
    REFERENCES `Ventas_Partes`.`compra_proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_pieza_bodega_clasificacion_pieza1`
    FOREIGN KEY (`clasificacion_pieza_id`)
    REFERENCES `Ventas_Partes`.`clasificacion_pieza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`bodega_tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`bodega_tienda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_salida` DATETIME NULL,
  `cantidad` INT NULL,
  `detalle` TEXT NULL,
  `fechar_ingreso` DATETIME NULL,
  `detalles_pieza_tienda_id` INT NOT NULL,
  `detalles_pieza_bodega_id` INT NOT NULL,
  `personal_ajepp_id` INT NOT NULL,
  PRIMARY KEY (`id`, `detalles_pieza_tienda_id`, `detalles_pieza_bodega_id`, `personal_ajepp_id`),
  INDEX `fk_bodega_tienda_detalles_pieza_tienda1_idx` (`detalles_pieza_tienda_id` ASC),
  INDEX `fk_bodega_tienda_detalles_pieza_bodega1_idx` (`detalles_pieza_bodega_id` ASC),
  INDEX `fk_bodega_tienda_personal_ajepp1_idx` (`personal_ajepp_id` ASC),
  CONSTRAINT `fk_bodega_tienda_detalles_pieza_tienda1`
    FOREIGN KEY (`detalles_pieza_tienda_id`)
    REFERENCES `Ventas_Partes`.`detalles_pieza_tienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_tienda_detalles_pieza_bodega1`
    FOREIGN KEY (`detalles_pieza_bodega_id`)
    REFERENCES `Ventas_Partes`.`detalles_pieza_bodega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_tienda_personal_ajepp1`
    FOREIGN KEY (`personal_ajepp_id`)
    REFERENCES `Ventas_Partes`.`personal_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`tienda_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`tienda_bodega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_salida` DATETIME NULL,
  `cantidad` INT NULL,
  `detalle` TEXT NULL,
  `fechar_retorno` DATETIME NULL,
  `detalles_pieza_tienda_id` INT NOT NULL,
  `detalles_pieza_bodega_id` INT NOT NULL,
  `personal_ajepp_id` INT NOT NULL,
  PRIMARY KEY (`id`, `detalles_pieza_tienda_id`, `detalles_pieza_bodega_id`, `personal_ajepp_id`),
  INDEX `fk_tienda_bodega_detalles_pieza_tienda1_idx` (`detalles_pieza_tienda_id` ASC),
  INDEX `fk_tienda_bodega_detalles_pieza_bodega1_idx` (`detalles_pieza_bodega_id` ASC),
  INDEX `fk_tienda_bodega_personal_ajepp1_idx` (`personal_ajepp_id` ASC),
  CONSTRAINT `fk_tienda_bodega_detalles_pieza_tienda1`
    FOREIGN KEY (`detalles_pieza_tienda_id`)
    REFERENCES `Ventas_Partes`.`detalles_pieza_tienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tienda_bodega_detalles_pieza_bodega1`
    FOREIGN KEY (`detalles_pieza_bodega_id`)
    REFERENCES `Ventas_Partes`.`detalles_pieza_bodega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tienda_bodega_personal_ajepp1`
    FOREIGN KEY (`personal_ajepp_id`)
    REFERENCES `Ventas_Partes`.`personal_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`contacto_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`contacto_proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pro_celular` VARCHAR(100) NULL,
  `pro_correo` VARCHAR(100) NULL,
  `pro_twiter` VARCHAR(45) NULL,
  `pro_fax` VARCHAR(45) NULL,
  `pro_telefono` VARCHAR(100) NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `proveedor_id`),
  INDEX `fk_contacto_proveedor_proveedor1_idx` (`proveedor_id` ASC),
  CONSTRAINT `fk_contacto_proveedor_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `Ventas_Partes`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iva` FLOAT NULL,
  `subtotal` FLOAT NULL,
  `total` FLOAT NULL,
  `fecha_venta` DATETIME NULL,
  `detalle` TEXT NULL,
  `tipo_pago_id` INT NOT NULL,
  `pie_cantidad` INT NULL,
  `pie_precio` FLOAT NULL,
  `cliente_id` INT NOT NULL,
  `personal_ajepp_id` INT NOT NULL,
  `detalles_pieza_tienda_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_pago_id`, `cliente_id`, `personal_ajepp_id`, `detalles_pieza_tienda_id`),
  INDEX `fk_ventas_tipo_pago1_idx` (`tipo_pago_id` ASC),
  INDEX `fk_ventas_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_ventas_personal_ajepp1_idx` (`personal_ajepp_id` ASC),
  INDEX `fk_ventas_detalles_pieza_tienda1_idx` (`detalles_pieza_tienda_id` ASC),
  CONSTRAINT `fk_ventas_tipo_pago1`
    FOREIGN KEY (`tipo_pago_id`)
    REFERENCES `Ventas_Partes`.`tipo_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Ventas_Partes`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_personal_ajepp1`
    FOREIGN KEY (`personal_ajepp_id`)
    REFERENCES `Ventas_Partes`.`personal_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_detalles_pieza_tienda1`
    FOREIGN KEY (`detalles_pieza_tienda_id`)
    REFERENCES `Ventas_Partes`.`detalles_pieza_tienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ventas_Partes`.`reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ventas_Partes`.`reportes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repor_fecha` DATETIME NOT NULL,
  `detalle` TEXT NOT NULL,
  `personal_ajepp_id` INT NOT NULL,
  PRIMARY KEY (`id`, `personal_ajepp_id`),
  INDEX `fk_reportes_personal_ajepp1_idx` (`personal_ajepp_id` ASC),
  CONSTRAINT `fk_reportes_personal_ajepp1`
    FOREIGN KEY (`personal_ajepp_id`)
    REFERENCES `Ventas_Partes`.`personal_ajepp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
