-- Insertar tipo de Vehiculo
INSERT INTO `ventas_partes`.`tipo_vehiculo` (`tipo_vehiculo`, `clasificacion_vehiculo`) VALUES ('Terrestre', 'Taxi');

-- Insertar Marca de Vehiculo
INSERT INTO `ventas_partes`.`marca_vehiculo` (`marca_vehiculo`, `tipo_vehiculo_id`) VALUES ('HYUNDAI','1');

-- Insertar Modelo Vehiculo
INSERT INTO `ventas_partes`.`modelo_vehiculo` (`marca_vehiculo_id`, `mod_vehiculo`, `mod_anio`, `procedencia`) VALUES ('1', 'GL-GLS', '2001', 'Seúl - Corea del Sur');

-- Insertar Clasificacion Piezas
INSERT INTO `ventas_partes`.`clasificacion_pieza` (`pi_nombre`) VALUES ('Etiqueta');
INSERT INTO `ventas_partes`.`clasificacion_pieza` (`pi_nombre`) VALUES ('Conjunto Gato');
INSERT INTO `ventas_partes`.`clasificacion_pieza` (`pi_nombre`) VALUES ('Motor');
-- Insertar Piezas Vehiculo
-- 05 Etiqueta
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '1', 'Etiqueta','Todas Num: 05203-02000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '1', 'Etiqueta Control','GEN, LHD, +2GB, +A08 Num: 32450-02580');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '1', 'Etiqueta Control', 'GEN, LHD, +2GB, +A08 Num: 32450-02581');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '1', 'Etiqueta Control', 'GEN, LHD, +2GB, +B07 Num: 32450-02570');
-- 09 Conjunto Gato
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Conjunto Gato', 'GEN Num: 09110-23000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Conjunto Gato', 'GEN, +A18 Num: 09110-02000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Conjunto Gato', 'GEN, +A18 Num: 09110-02100');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Conjunto Gato', 'GEN, -A18 Num: 09110-23000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Conjunto Gato', 'GEN, -A18 Num: 09110-02200');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Conjunto Gato', 'MES Num: 09110-23000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Conjunto Gato', 'MES Num: 09110-02200');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Etiqueta', 'GEN, +A18 Num: 09127-29000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Caja de Herramientas', 'Todas Num: 09149-33540');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Caja de Herramientas', 'Todas Num: 09149-02000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Caja de Herramientas', 'Todas Num: 09149-34000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Llave de Ruedas', 'Todas Num: 09131-28000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Llave de Ruedas', 'Todas Num: 09131-29000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Llave Fija 10x12', 'Todas Num: 09135-11210');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Alicates', 'Todas Num: 09145-11200');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '2', 'Destornilladores', 'Todas Num: 09146-11110');
-- 20 Motor
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Sub-Conjunto Motor', 'Todas, +2GB Num: 21101-02B00');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Sub-Conjunto Motor', 'Todas, -2GB Num: 21101-02C00');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto-Corto Motor', 'Todas, +2GB Num: 21102-02B00');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto-Corto Motor', 'GEN, -2GB Num: 21102-02B00');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto-Corto Motor', 'GEN, -2GB Num: 21102-02D00');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto-Corto Motor', 'Mes, -2GB Num: 21102-02D00');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Juego de Juntas Reparacion de Motor', 'Todas Num: 20910-02B00');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Juego de Juntas Reparacion de Motor GEN', 'Todas Num: 20920-02B00');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Espiga', 'Todas Num: 14303-06140');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Casquillo', 'Todas Num: 14331-10160');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Casquillo', 'Todas Num: 14331-06090');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 15716-13111');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tapa Selladora', 'Todas Num: 15732-30001');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Bloque de Cilindros', 'Todas Num: 21100-02700');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tapa de Perno', 'Todas Num: 21114-02511');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Filtro de Aceite de Estudio', 'Todas Num: 21141-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Interruptor de Presión Aceite', 'Todas Num: 94750-21030');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11400-08101');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11403-06181');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11403-06301');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Maquina de Tornillo', 'Todas Num: 12203-06141');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Anillo Retenedor', 'Todas Num: 14615-12005');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Enchufe', 'Todas Num: 15716-13111');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto de Cubierta', 'Todas Num: 21310-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tapa de Bonba de Aceite', 'Todas Num: 21313-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Estuche de Junta FR', 'Todas Num: 21411-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Anillo Reten de Aceite', 'Todas Num: 21421-21020');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Bomba de Aceite para Engranajes INR', 'Todas Num: 26112-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Bomba de Aceite para Engranajes OTR', 'Todas Num: 26113-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Embolo Descarga', 'Todas Num: 26122-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Muelle Descarga', 'Todas Num: 26123-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Retencion', 'Todas Num: 26124-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Filtro Aceite Motor', 'Todas Num: 26300-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Medidor de Nivel de Aceite', 'Todas Num: 26611-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Guía de Nivel de Aceite', 'Todas Num: 26612-02501');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Anillo "O"', 'Todas Num: 26614-35000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Anillo "O"', 'Todas Num: 26615-33000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11233-06101');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11233-06121');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11233-08201');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11403-06181');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11403-06141');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Cubierta Correa de Distribución', 'Todas Num: 21350-02710');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Correa de Distribución CVR', 'Todas Num: 21352-02700');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Bloque Placa Cilindro RR', 'Todas Num: 21431-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Caja Sello de Aceite RR', 'Todas Num: 21441-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Sello Aceite RR', 'Todas Num: 21443-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Estuche de Junta de Aceite', 'Todas Num: 21444-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Junta Liquida Motor', 'Todas Num: 21451-33A01');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Vivienda Cubierta', 'Todas Num: 21461-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Aceite de Motor Conjunto', 'Todas Num: 21510-02510');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Drenaje de Aceite', 'Todas Num: 21512-21000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Enchufe de Aceite de Junta', 'Todas Num: 21513-21000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pantalla Conjunto de Aceite', 'Todas Num: 26250-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pantalla de Junta de Aceite', 'Todas Num: 26259-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'GEN, -9AA Num: 11233-08251');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'GEN Num: 11234-10251');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'GEN Num: 11234-10301');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11361-10851');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11361-12001A');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Soporte de Motor de Soporte', 'Todas Num: 21681-02510');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto Tuerca', 'Todas Num: 21621-24000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto Soporte - Transaxle MTG', 'Todas Num: 21830-02050');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto Soporte Rodillo Tapón FR', 'Todas Num: 21840-02000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto Tuerca', 'Todas Num: 21845-24000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 21855-02000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11403-06221');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11403-08251');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Semental', 'RHD Num: 11513-08351');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Semental', 'GEN, LHD Num: 11513-08351');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Semental', 'MES Num: 11513-08351');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Semental', 'Todas Num: 11533-08255');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Semental', 'GEN, LHD Num: 11533-08325');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Abrazadera', 'Todas Num: 14720-22006');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Sellado de Tapones', 'Todas Num: 15732-30001');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Enchufe', 'Todas Num: 21131-32000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto de Cilindro de Cabeza', 'Todas Num: 22100-02700');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Asiento', 'Todas Num: 22112-02900');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Asiento', 'Todas Num: 22112-02910');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Escape de Asiento', 'Todas Num: 22113-02900');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Escape de Asiento', 'Todas Num: 22113-02910');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Entrada Guía', 'Todas Num: 22114-02900');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Entrada Guía', 'Todas Num: 22114-02910');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Entrada Guía', 'Todas Num: 22114-02920');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Escape', 'Todas Num: 22115-02900');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Escape', 'Todas Num: 22115-02910');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Válvula de Escape', 'Todas Num: 22115-02920');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Semental', 'Todas Num: 22125-21000');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Reten Aceite', 'Todas Num: 22144-21010');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Culata Junta', 'Todas Num: 22311-02700');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Culata de Perno', 'Todas Num: 22320-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Entrada de Refrigerante', 'Todas Num: 25632-02501');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'BYPASS Refrigerante de Manguera', 'Todas Num: 25472-02501');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto de Termostato', 'Todas Num: 25500-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Salida de Refrigerante', 'Todas Num: 25611-02502');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Anillo "O"', 'Todas Num: 25612-02501');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Estuche de Termostato de Junta', 'Todas Num: 25614-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Carcasa de Termostato', 'Todas Num: 25622-02501');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pezón', 'Todas Num: 25623-35500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Anillo "O"', 'Todas Num: 25633-02502');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Sensor Temperatura Refrigerante', 'Todas Num: 39220-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Tornillo', 'Todas Num: 11403-06281');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Espiga', 'MTA Num: 14303-08180');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pasador', 'Todas Num: 14311-05205');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Rodamiento Set CRK/SHF', 'Todas Num: 21020-02540');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Rodamiento Set CRK/SHF', 'Todas Num: 21020-02591');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Rodamiento Set CRK/SHF', 'Todas Num: 21020-02592');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'Todas, +2GB Num: 23040-02700');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02934');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02710');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02935');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02936');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02937');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02938');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'MES, -2GB Num: 23040-02710');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'MES, -2GB Num: 23040-02935');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'MES, -2GB Num: 23040-02936');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'MES, -2GB Num: 23040-02937');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'Todas, +2GB Num: 23040-02931');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'MES, -2GB Num: 23040-02938');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'Todas, +2GB Num: 23040-02932');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'Todas, +2GB Num: 23040-02933');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'Todas, +2GB Num: 23040-02934');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02700');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02931');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02932');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Pistón de Juego de Anillos', 'GEN, -2GB Num: 23040-02933');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Rodamiento Set C/ROD', 'Todas Num: 23060-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Rodamiento Set C/ROD', 'Todas Num: 23060-02591');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Rodamiento Set C/ROD', 'Todas Num: 23060-02592');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Cigueñal', 'GEN Num: 23111-02720');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Cigueñal', 'GEN Num: 23111-02721');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Cigueñal', 'MES Num: 23111-02721');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Cigueñal', 'ATA Num: 23112-02501');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Piñon Cigueñal', 'Todas Num: 23121-02511');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Polea Cigueñal', 'Todas Num: 23124-02510');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Arandela', 'Todas Num: 23126-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Perno Cigueñal', 'GEN Num: 23127-02500');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Perno Cigueñal', 'GEN Num: 23127-02501');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Perno Cigueñal', 'MES Num: 23127-02501');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Polea Cigueñal A/C', 'Todas, +9AA Num: 23151-02502');
INSERT INTO `ventas_partes`.`piezas_vehiculo` (`modelo_vehiculo_id`, `clasificacion_pieza_id`, `pie_nombre`, `pie_descripcion`) VALUES ('1', '3', 'Conjunto de Volante', 'MTA Num: 23200-02521');
